// For use with IDE plugins: https://github.com/svg/svgo#other-ways-to-use-svgo
module.exports = {
  floatPrecision: 2,
  gzip: true,
  multipass: true,
  pretty: true,
  plugins: [
    {
      name: 'preset-default',
      params: {
        overrides: {
          cleanupAttrs: true,
          cleanupEnableBackground: true,
          cleanupIDs: true,
          cleanupListOfValues: false,
          cleanupNumericValues: true,
          collapseGroups: true,
          convertColors: true,
          convertEllipseToCircle: true,
          convertPathData: true,
          convertShapeToPath: true,
          convertStyleToAttrs: true,
          convertTransform: true,
          inlineStyles: true,
          mergePaths: true,
          mergeStyles: true,
          minifyStyles: true,
          moveElemsAttrsToGroup: true,
          moveGroupAttrsToElems: true,
          removeComments: true,
          removeDesc: true,
          removeDimensions: true,
          removeDoctype: true,
          removeEditorsNSData: true,
          removeEmptyAttrs: true,
          removeEmptyContainers: true,
          removeEmptyText: true,
          removeHiddenElems: true,
          removeMetadata: true,
          removeNonInheritableGroupAttrs: true,
          removeRasterImages: true,
          removeScriptElement: true,
          removeStyleElement: true,
          removeTitle: true,
          removeUnknownsAndDefaults: true,
          removeUnusedNS: true,
          removeUselessDefs: true,
          removeUselessStrokeAndFill: true,
          removeViewBox: false,
          removeXMLNS: false,
          removeXMLProcInst: true,
          reusePaths: false,
          sortAttrs: false,
          sortDefsChildren: true,
        },
      },
    },
  ],
};
